### ISSUE TITLE
Yes, but ...

### ISSUE THREAD

**Issue by rundef** [Qix-/tabs-are-better-than-spaces#1]
[Spaces earn you more money !](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/)

**Comment by Qix-** [comment]
Prime example of correlation vs. causation. IDEs default to spaces, so most people are going to use them.

Also, most people follow company standards (as they should), and those standards are almost always spaces.

Maybe the tabs camp is just filled with more _flexible_ people, and money can't buy a good personality.

;)
